apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Chart.Name }}-db-secret"
  labels:
    {{- include "helper.labels" . | nindent 4 }}
type: kubernetes.io/basic-auth
stringData:
  username: "{{ .Values.secrets.POSTGRES_USER }}"
  password: "{{ .Values.secrets.POSTGRES_PASSWORD }}"
