{
 "title": "Kubernetes Cluster",
 "description": "Cluster level overview of workloads deployed, based on prometheus metrics exposed by kubelet, node-exporter, nginx ingress controller",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Current Connections",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(nginx_connections_total{type=\"active\"})"
    }
   ]
  },
  {
   "title": "Least CPU Idle",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 2, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "sort_desc(avg(rate(node_cpu_seconds_total{mode=\"idle\"}[2m])) by (instance))"
    }
   ]
  },
  {
   "title": "Min Space",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 2, "x": 6, "y": 0 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "min(node_filesystem_avail_bytes{mountpoint!~\".*(serviceaccount|proc|sys).*\"}/node_filesystem_size_bytes{mountpoint!~\".*(serviceaccount|proc|sys).*\"})"
    }
   ]
  },
  {
   "title": "Min Mem",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 2, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemAvailable_bytes/node_memory_MemTotal_bytes) by (instance)"
    }
   ]
  },
  {
   "title": "Request Time",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 2, "x": 10, "y": 0 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(irate(http_request_duration_seconds_count{status=\"200\", method=\"GET\"}[10m]))"
    }
   ]
  },
  {
   "title": "Pod Restarts",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 2, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(sum by (pod)(delta(kube_pod_container_status_restarts_total[15m]) > 0))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pods Restarted",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 14, "y": 0 },
   "targets": [
    {
     "expr": "sum by (pod)(delta(kube_pod_container_status_restarts_total[15m]) > 0)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pods Running Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (kube_pod_status_phase{}) by (phase)",
     "legendFormat": "{{ phase }}"
    },
    {
     "expr": "kubelet_running_pod_count{kubernetes_io_role =~ \".*node.*\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Load 1m",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_load1", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes + node_memory_Buffers_bytes + node_memory_Cached_bytes",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Idle Avg",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(rate(node_cpu_seconds_total{mode=\"idle\"}[2m])) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Node Storage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "min(node_filesystem_avail_bytes{mountpoint!~\".*(serviceaccount|proc|sys).*\", device!=\"overlay\"}/node_filesystem_size_bytes{mountpoint!~\".*(serviceaccount|proc|sys).*\", device!=\"overlay\"}) by (device, instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk IO s",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_io_time_seconds_total[2m])",
     "legendFormat": "{{instance}} {{device}}"
    }
   ]
  },
  {
   "title": "Top 5 Memory Intense Pods",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 13 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "topk(5,sum(container_memory_usage_bytes{image!=\"\"}) by (pod))",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "TOP CPU Containers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5, sum(rate(container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",container_name!=\"POD\"}[2m])) by (pod, container_name))",
     "legendFormat": "{{ container_name }} in {{ pod_name }}"
    }
   ]
  }
 ]
}
{
 "title": "Orchestration",
 "description": "Overview of Pipeline Orchestration",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Queue: Finished Jobs",
   "type": "stat",
   "description": "Total number of finished jobs in the specified time interval",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "floor(increase(orchestration_rq_jobs_total{queue=\"orchestration_queue\",status=\"finished\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Queue: Failed Jobs",
   "type": "stat",
   "description": "Total number of failed jobs in the specified time range",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "floor(increase(orchestration_rq_jobs_total{queue=\"orchestration_queue\",status=\"failed\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Queue: Successful Job Ratio (Total)",
   "type": "gauge",
   "description": "Ratio of overall successful jobs",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "scalar(orchestration_rq_jobs_total{queue=\"orchestration_queue\", status=\"finished\"}) / (scalar(orchestration_rq_jobs_total{queue=\"orchestration_queue\", status=\"finished\"}) + scalar(orchestration_rq_jobs_total{queue=\"orchestration_queue\", status=\"failed\"}))"
    }
   ]
  },
  {
   "title": "Total number of jobs by status",
   "type": "graph",
   "gridPos": { "h": 5, "w": 15, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "orchestration_rq_jobs_total{status=~\"finished|failed\"}",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Processed Document Collections",
   "type": "stat",
   "description": "Total count of successfully processed document collections",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "orchestration_pipeline_duration_perpage_count"
    }
   ]
  },
  {
   "title": "Total Average Duration per Job",
   "type": "stat",
   "description": "Total Average Duration per Job",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "orchestration_pipeline_duration_total_sum / orchestration_pipeline_duration_total_count"
    }
   ]
  },
  {
   "title": "Average Duration per Job",
   "type": "stat",
   "description": "Avg. Duration per Job over the specified time range",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(orchestration_pipeline_duration_total_sum[$__range]) / increase(orchestration_pipeline_duration_total_count[$__range])"
    }
   ]
  },
  {
   "title": "All Time Processed Pages",
   "type": "stat",
   "description": "Total number of pages successfully processed",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "orchestration_pipeline_pages_sum"
    }
   ]
  },
  {
   "title": "Processed Pages",
   "type": "stat",
   "description": "Total number of pages successfully processed in the specified time range",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(increase(orchestration_pipeline_pages_sum[$__range]))"
    }
   ]
  },
  {
   "title": "All Time Average Duration per Page",
   "type": "stat",
   "description": "Avg. Duration per Page last 5m",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "orchestration_pipeline_duration_total_sum / orchestration_pipeline_pages_sum"
    }
   ]
  },
  {
   "title": "Average Duration per Page",
   "type": "stat",
   "description": "Duration per Page averaged over the specified time range",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(orchestration_pipeline_duration_total_sum[$__range]) / increase(orchestration_pipeline_pages_sum[$__range])"
    }
   ]
  },
  {
   "title": "Average Duration per Job in Time Range",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "increase(orchestration_pipeline_duration_total_sum[$__range]) / increase(orchestration_pipeline_duration_total_count[$__range])",
     "legendFormat": "Average Duration per Job in Last Hour"
    }
   ]
  },
  {
   "title": "Average Duration per Page in Time Range",
   "type": "graph",
   "description": "Duration per Page averaged over the time range",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(orchestration_pipeline_duration_total_sum[$__range]) / rate(orchestration_pipeline_pages_sum[$__range])",
     "legendFormat": "Average Duration per Page in Last Hour"
    }
   ]
  },
  {
   "title": "95 Percentile of Processing Duration per Job",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(orchestration_pipeline_duration_total_bucket[5m])) by (le))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "95 Percentile of Processing Duration per Page",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(orchestration_pipeline_duration_perpage_bucket[5m])) by (le))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "RQ Workers",
   "type": "stat",
   "description": "Number of RQ workers available in orchestrator",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(orchestration_rq_workers)" }
   ]
  },
  {
   "title": "Orchestration: Queue Workers Capacity",
   "type": "graph",
   "description": "Capacity of the queue workers of the orchestrators",
   "gridPos": { "h": 5, "w": 21, "x": 3, "y": 25 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(count(orchestration_rq_workers{state=\"busy\",queues=\"orchestration_queue\"}) / count(orchestration_rq_workers{queues=\"orchestration_queue\"})) * 100",
     "legendFormat": "Busy workers"
    },
    {
     "expr": "(count(orchestration_rq_workers{state=\"idle\",queues=\"orchestration_queue\"}) / count(orchestration_rq_workers{queues=\"orchestration_queue\"})) * 100",
     "legendFormat": "Idle Workers"
    }
   ]
  },
  {
   "title": "Orchestration Jobs in Registries",
   "type": "bargauge",
   "description": "Number of jobs that are currently in the orchestration registries grouped by status registry",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "orchestration_rq_registry", "legendFormat": "{{status}}" }
   ]
  },
  {
   "title": "Orchestration Jobs in Registries",
   "type": "graph",
   "description": "Number of jobs that are currently in the orchestration registries grouped by status registry",
   "gridPos": { "h": 6, "w": 14, "x": 10, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "yaxes": [
    { "format": "string" }
   ],
   "targets": [
    { "expr": "orchestration_rq_registry", "legendFormat": "{{status}}" }
   ]
  },
  {
   "title": "Distribution of Job Size in Pages",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "sum(increase(orchestration_pipeline_pages_bucket[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Distribution of Job Duration",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "expr": " sum(increase(orchestration_pipeline_duration_total_bucket[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}
{
 "title": "Pipeline Microservices",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "microservice",
    "query": "label_values(pipeline_request_processing_response_total, kubernetes_name)"
   }
  ]
 },
 "panels": [
  { "title": "$microservice", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "microservice" },
  {
   "title": "Requests in Progress",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (kubernetes_name) (pipeline_request_in_progress{kubernetes_name=\"$microservice\"})"
    }
   ]
  },
  {
   "title": "$microservice total responses",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (response_code) (pipeline_request_processing_response_total{kubernetes_name=\"$microservice\"})",
     "legendFormat": "{{response_code}}"
    }
   ]
  },
  {
   "title": "$microservice 95 Percentile of Request Duration in last hour",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(increase(pipeline_request_processing_time_bucket{kubernetes_name=\"$microservice\"}[1h])) by (le))"
    }
   ]
  },
  {
   "title": "$microservice request duration",
   "type": "heatmap",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "sum(increase(pipeline_request_processing_time_bucket{kubernetes_name=\"$microservice\"}[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "$microservice Response Codes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (response_code) (pipeline_request_processing_response_total{kubernetes_name=\"$microservice\"})",
     "legendFormat": "{{response_code}}"
    }
   ]
  }
 ]
}