apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress_class }}
    nginx.ingress.kubernetes.io/proxy-buffer-size: '8k'
  name: keycloak-ingress
spec:
  tls:
    - hosts:
        - {{ .Values.hostname_prefix }}.{{ .Values.http_application_routing_zone_name }}
  rules:
    - host: {{ .Values.hostname_prefix }}.{{ .Values.http_application_routing_zone_name }}
      http:
        paths:
        - pathType: ImplementationSpecific
          backend:
            service:
              name: service-keycloak
              port:
                number: 9010
          path: /auth