#lifecycle:
  # preStop:
  #   exec:
  #     command: ["/bin/sh", "-c", "echo Hello from the postStart handler > /usr/share/message"]
  #postStart:
  #  exec:
  #    command:
  #      - bash
  #      - -c
  #      - |
  #        #!/bin/bash
  #        # Add a template to adjust number of shards/replicas
  #        TEMPLATE_NAME=my_template
  #        INDEX_PATTERN="logstash-*"
  #        SHARD_COUNT=8
  #        REPLICA_COUNT=1
  #        ES_URL=http://localhost:9200
  #        while [[ "$(curl -s -o /dev/null -w '%{http_code}\n' $ES_URL)" != "200" ]]; do sleep 1; done
  #        curl -XPUT "$ES_URL/_template/$TEMPLATE_NAME" -H 'Content-Type: application/json' -d'{"index_patterns":['\""$INDEX_PATTERN"\"'],"settings":{"number_of_shards":'$SHARD_COUNT',"number_of_replicas":'$REPLICA_COUNT'}}'
  
resources:
  requests:
    cpu: "300m"
    memory: "500Mi"
  limits:
    cpu: "1000m"
    memory: "2Gi"

volumeClaimTemplate:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 30Gi
  storageClassName: default