kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: jaeger-ingress
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress_class }}
    kubernetes.io/tls-acme: 'true'
    nginx.ingress.kubernetes.io/auth-signin: 'https://$host/oauth2/start?rd=$request_uri'
    nginx.ingress.kubernetes.io/auth-url: 'https://$host/oauth2/auth'
    nginx.ingress.kubernetes.io/proxy-body-size: '0'
spec:
  tls:
    - hosts:
        - {{ .Values.hostname_prefix }}.{{ .Values.http_application_routing_zone_name }}
  rules:
    - host: {{ .Values.hostname_prefix }}.{{ .Values.http_application_routing_zone_name }}
      http:
        paths:
        - pathType: ImplementationSpecific
          backend:
            service:
              name: tracing-jaeger-operator-jaeger-query
              port:
                number: 16686
          path: /
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress_class }}
    nginx.ingress.kubernetes.io/proxy-buffer-size: '8k'
  labels:
    app: jaeger-oauth2-proxy
  name: jaeger-oauth2-proxy
spec:
  tls:
    - hosts:
        - {{ .Values.hostname_prefix }}.{{ .Values.http_application_routing_zone_name }}
  rules:
    - host: {{ .Values.hostname_prefix }}.{{ .Values.http_application_routing_zone_name }}
      http:
        paths:
        - pathType: ImplementationSpecific
          path: /oauth2
          backend:
            service:
              name: oauth2-proxy
              port:
                number: 4180