name: ARM Template 

on:
  push:
    branches:
      - none
  workflow_dispatch:

jobs:
  AKS:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: AKS_Install
      run: |
        az login --service-principal -u ${{ secrets.SERVICE_PRINCIPAL_ID }} -p ${{ secrets.SERVICE_PRINCIPAL_KEY }} --tenant ${{ secrets.TENANT_ID }}
        deploymentName='MyDeployment'
            cd aksterraform/environments/azure
            ls
            export ARM_CLIENT_ID=${{ secrets.SERVICE_PRINCIPAL_ID }}
            export ARM_CLIENT_SECRET=${{ secrets.SERVICE_PRINCIPAL_KEY }}
            export ARM_TENANT_ID=${{ secrets.TENANT_ID }}
            export ARM_SUBSCRIPTION_ID=$(subscriptions-name)
            terraform init
            terraform plan
            terraform apply -auto-approve
