name: ARM Template 

on:
  push:
    branches:
      - none
  workflow_dispatch:

jobs:
  accountsOpenAI:
    runs-on: ubuntu-latest
     
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Azure_OpenAI_Deploy
      run: |
        az login --service-principal -u ${{ secrets.SERVICE_PRINCIPAL_ID }} -p ${{ secrets.SERVICE_PRINCIPAL_KEY }} --tenant ${{ secrets.TENANT_ID }}
        deploymentName='MyDeployment'
        az deployment group create --resource-group 'S2P_GitHub_PoC' --name MyDeployment --template-file accountsOpenAI.json
