name: ARM Template 

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  say_hello:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Print ContainerRegistry Variable
      run: az login --service-principal -u 5e271e75-ae51-43b3-9aa6-e29b01112f73 -p jOa8Q~snex0rc3Pqo4f_f8XXulgj8t7N-l~bsbgx --tenant 6d51934d-cd16-4aa4-8faf-18a60cfc6ae7
      env:
        CONTAINERREGISTER_NAME: ${{ vars.CONTAINERREGISTER_NAME }}
