name: ARM Template 

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  say_hello:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Print ContainerRegistry Variable
      run: echo $CONTAINERREGISTER_NAME
      env:
        CONTAINERREGISTER_NAME: ${{ vars.CONTAINERREGISTER_NAME }}
