name: ARM Template 

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  say_hello:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Print ContainerRegistry Variable
      run: | 
        az login --service-principal -u ${{ secrets.SERVICE_PRINCIPAL_ID }} -p ${{ secrets.SERVICE_PRINCIPAL_KEY }} --tenant ${{ secrets.TENANT_ID }}
        ls
        deploymentName='MyDeployment'
        sed -i "s|{{.containerregistryname}}|$(CONTAINERREGISTER_NAME)|" Container_Registry.json
        sed -i "s|{{.location}}|$(LOCATION_NAME)|" Container_Registry.json   
        cat ContainerRegistry.json
        az deployment group create --resource-group $(resource-group-name) --name $deploymentName --template-file Container_Registry.json


