name: ARM Template 

on:
  push:
    branches:
      - none
  workflow_dispatch:

jobs:
  Container_Registry:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Container_Registry_Install
      run: |
        if [ "${{ secrets.INFRA_STATUS_CONTAINER_REGISTER }}" == "yes" ]; then
          az login --service-principal -u ${{ secrets.SERVICE_PRINCIPAL_ID }} -p ${{ secrets.SERVICE_PRINCIPAL_KEY }} --tenant ${{ secrets.TENANT_ID }}
          deploymentName='MyDeployment'
          echo "a"
          sed -i "s|{{.containerregistryname}}|${{ vars.CONTAINERREGISTER_NAME }}|" Container_Registry.json
          sed -i "s|{{.location}}|${{ vars.LOCATION_NAME }}|" Container_Registry.json   
          cat Container_Registry.json   
          az deployment group create --resource-group ${{ vars.RESOURCEGROUP_NAME }} --name $deploymentName --template-file Container_Registry.json
        else
          echo "INFRA_STATUS_CONTAINER_REGISTER is not 'yes'. Skipping..."
        fi          

